# Generated by Django 5.0.4 on 2024-04-18 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
                ('description', models.TextField(blank=True, verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_firstname', models.CharField(max_length=100, verbose_name='Фамилия клиента')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество клиента')),
                ('delivery_address', models.CharField(max_length=100, verbose_name='Адрес доставки')),
                ('delivery_type', models.CharField(choices=[('MG', 'Самовывоз'), ('CR', 'Курьер'), ('PP', 'Точка выдачи заказов')], default='MG', max_length=2, verbose_name='Способ доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к заказу')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('datetime_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'permissions': [('change_delivery_type', 'Возможность изменить тип доставки'), ('can_finish_order', 'Возможность завершить заказ')],
            },
        ),
        migrations.CreateModel(
            name='Parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товара',
            },
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название исполнителя')),
                ('description', models.TextField(blank=True, verbose_name='Описании исполнителя')),
                ('photo', models.ImageField(blank=True, upload_to='performers/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поставщика')),
                ('agent_firstname', models.CharField(max_length=100, verbose_name='Фамилия агента')),
                ('agent_name', models.CharField(max_length=100, verbose_name='Имя агента')),
                ('agent_patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество агента')),
                ('agent_telephone', models.CharField(max_length=100, verbose_name='Телефон агента')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес компании')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Pos_parametr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение характеристики')),
                ('parametr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.parametr', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Позиция характеристики',
                'verbose_name_plural': 'Позиции характеристики',
            },
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставка',
                'verbose_name_plural': 'Поставки',
            },
        ),
        migrations.CreateModel(
            name='Pos_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во пластинок')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Позиция поставки',
                'verbose_name_plural': 'Позиции поставки',
            },
        ),
        migrations.CreateModel(
            name='Vinyl_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Цена')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('datetime_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('image', models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Изображение')),
                ('is_exist', models.BooleanField(default=True, verbose_name='Существует?')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.genre', verbose_name='Жанр')),
                ('parametr', models.ManyToManyField(through='plastinkishop.Pos_parametr', to='plastinkishop.parametr', verbose_name='Характеристики')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.performer', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Пластинка',
                'verbose_name_plural': 'Пластинки',
            },
        ),
        migrations.AddField(
            model_name='supply',
            name='vinyl_record',
            field=models.ManyToManyField(through='plastinkishop.Pos_supply', to='plastinkishop.vinyl_record', verbose_name='Пластинки'),
        ),
        migrations.AddField(
            model_name='pos_supply',
            name='vinyl_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.vinyl_record', verbose_name='Пластинка'),
        ),
        migrations.AddField(
            model_name='pos_parametr',
            name='vinyl_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.vinyl_record', verbose_name='Пластинка'),
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во пластинок')),
                ('discount', models.IntegerField(verbose_name='Скидки на позицию')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.order', verbose_name='Поставка')),
                ('vinyl_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.vinyl_record', verbose_name='Пластинка')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='vinyl_record',
            field=models.ManyToManyField(through='plastinkishop.Pos_order', to='plastinkishop.vinyl_record', verbose_name='Пластинки'),
        ),
    ]
