# Generated by Django 5.0.4 on 2024-04-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastinkishop', '0002_supply_date_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='date_supply',
            field=models.DateTimeField(verbose_name='Дата поставки'),
        ),
    ]
