# Generated by Django 5.0.4 on 2024-04-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plastinkishop', '0003_alter_supply_date_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos_order',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидки на позицию'),
        ),
        migrations.AlterField(
            model_name='pos_order',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plastinkishop.order', verbose_name='Заказ'),
        ),
    ]
